### ISSUE TITLE
Unused helper parameters.

### ISSUE THREAD

**Issue by pnelson** [goji/ctx-csrf#7]
`Token`, `FailureReason`, `TemplateField` and `mask` in `helpers.go` don't need the `r *http.Request` parameter. Are there any plans to clean that up? Simply removing it would be a breaking change. How would you like to deal with it, if at all?

**Comment by elithrar** [comment]
They were left for future planning (e.g. Go 1.7's `r.Context()`) but the shallow copy in 1.7 doesn't allow them to be used as such. Changing would break, and since passing the pointer has no real impact, we have to live with it.

Note that since Go 1.7 you can use https://github.com/gorilla/csrf as well, which supports `context.Context` in the request.
